### ISSUE TITLE
missing some values in summary objects

### ISSUE THREAD

**Issue by Yilinwang** [clic-lab/newsroom#10]
There are only ['url', 'archive', 'title', 'date', 'text', 'summary', 'density', 'coverage', 'compression', 'compression_bin', 'coverage_bin', 'density_bin'] in summary objects. While ['subset', 'publication'] which stated on your website are missing. Without 'subset' we can not compare our result to those on the leaderboard. Can you provide those information? Thanks.

**Comment by astariul** [comment]
See #16
