### ISSUE TITLE
evaluation tools

### ISSUE THREAD

**Issue by dantheman3333** [clic-lab/newsroom#14]
Will the evaluation tools be made available anytime soon? If not, do you recommend a specific python wrapper for rouge? Thanks

**Comment by grusky** [comment]
Hi! I'm hoping to update the repo soon with the tools, they are mostly complete but need testing. I would recommend using the PERL reference ROUGE script directly, if possible. For Python, I would recommend pyrouge (https://github.com/bheinzerling/pyrouge) — though pyrouge has problems with enabling/disabling stemming, so you should make sure that it is using with the correct ROUGE parameters that you have chosen to evaluate with.
