### ISSUE TITLE
"Publication" key is missing from the extracted dataset.

### ISSUE THREAD

**Issue by sb1992** [clic-lab/newsroom#15]
I downloaded and extracted the dataset using the script but the "publication" key is missing from the extracted train.data file.

**Comment by grusky** [comment]
Hi, sorry for my late reply! The publication key can almost always be inferred from the URL, though there are a couple tricky cases that make it challenging to do this programmatically with the URL lists + download script. (The publication key is in the full dataset, however, available here: https://summari.es/download/)
