### ISSUE TITLE
I get an abort error when trying to scraping the dataset. 

### ISSUE THREAD

**Issue by Shashi456** [clic-lab/newsroom#17]
![image](https://user-images.githubusercontent.com/18056781/54878724-9b3b0080-4e56-11e9-9635-fcb543b324d2.png)

Can you help me out here, or is there any link i could directly download the dataset from? @yoavartzi @grusky

**Comment by yoavartzi** [comment]
We recently updated a form to get the full version. Please see here:
https://summari.es/download/
Select the top radio button and and fill in your details.
