### ISSUE TITLE
Some of the URLs are missing both from the Web rchive and original web sites

### ISSUE THREAD

**Issue by yjernite** [clic-lab/newsroom#2]
After running the crawler a couple of times with a reduced number of workers and even exactness 4, I have around 100 articles still missing in both the dev andd test set (train is still running, currently missing about 2700). For example:
https://newoldage.blogs.nytimes.com/2009/12/03/ccrc-fees-prepare-to-be-bewildered/index.html

Others are on the original websites, but not found on the WebArchive
https://www.nytimes.com/2010/10/21/opinion/21kristof.html
https://web.archive.org/web/*/https://www.nytimes.com/2010/10/21/opinion/21kristof.html
(All webarchive saves redirect to errors)

Any ideas on what went wrong there? Could there be a fix to get them directly from the sites when available? I can post the full lists if that's helpful.

**Comment by grusky** [comment]
Sorry for the late reply! Are you still seeing this issue? What I've noticed while scraping is that some Archive pages are not always available, and sometimes are temporarily down but reappear later.

It looks like the first link you shared is still not available on Archive.org -- hopefully not permanently. The second one is available, though ([here, for example](https://web.archive.org/web/20151009054157/https://www.nytimes.com/2010/10/21/opinion/21kristof.html)). It looks like using exactness causes Archive to include non-200 links, which is causing the problem. For now, using exactness=3 seems to work for this page. In the future, I may add another argument to this script that uses another Archive.org API that, while slower, would prevent the Archive.org automatic redirection causing this problem.

I also have a copy of the complete dataset, send me an email (newsroom@summari.es) if you're still missing pages!
