### ISSUE TITLE
ModuleNotFoundError: No module named 'newsroom'

### ISSUE THREAD

**Issue by Shanzaay** [clic-lab/newsroom#22]
Hi. I am getting this module error. am I suppose to download it somewhere or do I need a newsroom.py file or something? Because I can't seem to find any file in the code. What am I missing?

**Comment by grusky** [comment]
Hi, were you able to pip install the Newsroom module with this?

```
pip install -e git+git://github.com/clic-lab/newsroom.git#egg=newsroom
```

If so, were there any errors/warnings on install?

**Comment by Shanzaay** [comment]
I did that and it installed successfully without any problem. But when i
execute the code i still get the module error.
