### ISSUE TITLE
data extraction error

### ISSUE THREAD

**Issue by shashiongithub** [clic-lab/newsroom#3]
I am getting this error 

_pickle.PicklingError: Can't pickle <function Article.process at 0x7f5f2ab56d90>: attribute lookup process on newsroom.build.filter failed

when using the following command:

newsroom-extract --archive dev.archive --dataset dev.data

I am running it with Python3.4.

**Comment by shashiongithub** [comment]
Python 3.6 does not have this problem!

**Comment by grusky** [comment]
This is good to know, I'll update the readme -- thanks!
