### ISSUE TITLE
Some articles have empty summaries, and scrape script doesn't always detect broken links

### ISSUE THREAD

**Issue by mgrenander** [clic-lab/newsroom#4]
Hi, thanks a lot for this great dataset. I have been looking forward to training models on it but I ran into two issues.

The first is related to #2 . Some of the WebArchive links redirect for some reason and the original article is lost. For example:
<https://web.archive.org/web/2014013019id_/http://www.nytimes.com/2014/01/31/world/europe/ukraine-unrest.html>

For this issue, it can be solved by the comment in #2 , i.e. using exactness 3. However it is problematic for anyone who does not set exactness to 3, since the ``newsroom-scrape`` script doesn't detect the broken link. So the malformed article-summary pair ends up in the final dataset.

The second issue is that some summaries are empty. For example:
<http://latimesblogs.latimes.com/technology/2011/08/how-to-opt-out-of-linkedin-sharing-your-data-with-third-parties.html>

In this case, should the article be excluded from the dataset? I don't see how a meaningful summary can be extracted from this web page.

**Comment by grusky** [comment]
I have a fix in progress for the redirecting issue, though I'm still not sure why Archive.org does not preserve all of the original exact article links. If you email me (newsroom@summari.es), I can share the remaining data with you, including the missing pages.

**Comment by mgrenander** [comment]
I agree - it is really strange. Thank you, I will send an email!
