### ISSUE TITLE
When will the complete dataset available?

### ISSUE THREAD

**Issue by bckim92** [clic-lab/newsroom#5]
Thanks for your hard work and great dataset.
When is the estimated release date for full newsroom dataset?

**Comment by grusky** [comment]
I'm hoping to have the dataset available to download online very soon! In the meantime, send me an email (newsroom@summari.es) and I can share a temporary link for the data. Thanks!

**Comment by bckim92** [comment]
Thank you for your answer. I will send you an email :)
