### ISSUE TITLE
thin.rar download URL unreacheable

### ISSUE THREAD

**Issue by sohamsengupta17** [clic-lab/newsroom#7]
https://summari.es/files/thin.tar can't be reached. When I try from the browser the download fails at around 20 MB each time. Using wget the following error is received:
Connecting to summari.es:80... connected!
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://summari.es/files/thin.tar [following]
--13:16:19--  ftp://https:21/%2Fsummari.es/files/thin.tar
           => `thin.tar'
Connecting to https:21...
https: Host not found
 
Is there any mirror to the thin.rar file?

**Comment by grusky** [comment]
Thanks for telling me! It looks like it may have been down temporarily but seems to be back up now. If you're still having trouble downloading it, email me at newsroom@summari.es and I can share the file directly with you.
