### ISSUE TITLE
Syntax error when newsroom-scrape uses python concurrent library

### ISSUE THREAD

**Issue by Rhuax** [clic-lab/newsroom#9]
Hi,

whenever I launch newsroom-scrape I get the SyntaxError from the concurrent library:

> Traceback (most recent call last):
>   File "/usr/local/bin/newsroom-scrape", line 11, in <module>
>     load_entry_point('newsroom', 'console_scripts', 'newsroom-scrape')()
>   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 480, in load_entry_point
>     return get_distribution(dist).load_entry_point(group, name)
>   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
>     return ep.load()
>   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2324, in load
>     return self.resolve()
>   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2330, in resolve
>     module = __import__(self.module_name, fromlist=['__name__'], level=0)
>   File "/home/crow/src/newsroom/newsroom/__init__.py", line 2, in <module>
>     from . import build
>   File "/home/crow/src/newsroom/newsroom/build/__init__.py", line 1, in <module>
>     from .download import Downloader
>   File "/home/crow/src/newsroom/newsroom/build/download.py", line 2, in <module>
>     from concurrent.futures import ThreadPoolExecutor
>   File "/usr/local/lib/python3.6/dist-packages/concurrent/futures/__init__.py", line 8, in <module>
>     from concurrent.futures._base import (FIRST_COMPLETED,
>   File "/usr/local/lib/python3.6/dist-packages/concurrent/futures/_base.py", line 381
>     raise exception_type, self._exception, self._traceback
>                         ^
> SyntaxError: invalid syntax

I think it's due to the use of python3 with a library written for python2. What can I do? I'm using python3

**Comment by grusky** [comment]
Do you have the [backported version](https://pypi.org/project/futures/) of the concurrent futures packages installed? It might be masking the standard implementation provided in Python 3.6. The line triggering the syntax error seems to only occur in the backported "futures" library:

https://github.com/agronholm/pythonfutures/blob/28fa404639a702c32a18a1a411409f1aab8ab464/concurrent/futures/_base.py#L414
